package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Friday, November 13, 2015 11:06:44 AM MSK
*/

public interface HelloOperations 
{
  String sayHello (String str);
  void shutdown ();
} // interface HelloOperations
